### PR TITLE
Replaces legacy reputation contract with new contract.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Retained old serpent legacyRep contract because a number of tests depend on it and I don't want to sink time into fixing them yet.

I put the code in `src/` so other contracts can reference it if necessary (e.g., for legacy rep migration process) but I have excluded it from being uploaded with everything else in the test suite.

Contracts should be byte-for-byte compatible with what is uploaded to main network (though I cleaned them up to match our team style and pass linter checks).

### CODE REVIEW

**Comment by joeykrug** [comment]
Looks like linter is getting ran on it causing build to fail

**Comment by MicahZoltu** [comment]
@beaugunderson Do you happen to know if the linter supports inline ignores?  Not only do we need to ignore these errors here, but we'll need to ignore them for all of our ERC20 contracts as well.  The interface defines these as lowercase, but the linter wants all constants uppercase.

**Comment by MicahZoltu** [comment]
Apparently it doesn't support it.  :'(  https://github.com/duaraghav8/Solium/issues/1

Should we disable this particular check then?

**Comment by joeykrug** [comment]
Yeah let's disable this check for now

**Comment by beaugunderson** [comment]
@MicahZoltu seems straightforward to add inline ignores to Solium; I'll work up a PR

**Comment by MicahZoltu** [comment]
Check disabled and CI green.  Recommend we not wait for Solium to update to merge this.  :)  (though, huge thanks @beaugunderson!)

**Comment by beaugunderson** [comment]
yeah definitely don't wait for that, assume we'll want to use it elsewhere though :)

**Pull request merged**
