### PR TITLE
Universe created event

### PR DESCRIPTION
**Pull request by nuevoalex**
Just adding a log

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Is this part of Augur node requirements, or something else?

**Comment by nuevoalex** [comment]
There was a one off issue for this event specifically.

The issue says it is also needed for the EventEmitter contract for testing, but I imagine it is needed by the Augur Node.

**Comment by MicahZoltu** [comment]
We have discussed having all these logs come from Augur.sol.  Thoughts?

**Comment by nuevoalex** [comment]
The question to me if we did that is how Augur.sol will do trust checks on the callers. Doing so will probably increase gas costs which seems wasteful just to centralized logging.

This is assuming we care about keeping people from messing up logs.

**Comment by MicahZoltu** [comment]
The argument for centralizing the logging is that it makes it possible to query for them.  When we fetch logs, we need to provide the contract that wrote the log.  This is difficult for logs like create universe because we can't know the address of the created universe until _after_ it is created which means we can't actually fetch the log that tells us the address of the created universe. The same goes for any operation that creates a contract.

Also, it is simpler for consumers to query a single log source than to query across 100s or 1000s of sources.

We should discuss this with the Augur node team.

**Pull request closed without merging**
