### PR TITLE
Dont adjust OI on Set actions

### PR DESCRIPTION
**Pull request by nuevoalex**
We recently changed to a new OI scheme of immediately reducing Universe OI by all of a market's outstanding complete sets at finalization.

This is needed to prevent leakage from the failure to sell outstanding shares and leakage from invalid payouts since the claimed amount for a set will be less than what was paid (even before fees)

In doing this however I forgot to restrict further OI modification for that market, which is needed since otherwise someone could buy sets then claim proceeds which would make Universe OI increase but never decrease from that action.

### CODE REVIEW

**Comment by epheph** [comment]
What if someone bought complete sets before finalization, but turned them in after finalization, instead of claiming proceeds? Not sure why they would, but it seems we would leak that way?

**Comment by nuevoalex** [comment]
At finalization all outstanding complete sets OI is decremented, so theyd be accounted for then

**Comment by nuevoalex** [comment]
Claiming proceeds never affects OI and since this is past finalization buying or selling complete sets wont either

**Comment by epheph** [comment]
Ahh, got it, so you're basically freezing any impact a finalize market has on OI. 🦊

**Pull request merged**
