### PR TITLE
Fix markdown block in README.md

### PR DESCRIPTION
**Pull request by tomdev**
A backtick was missing causing the highlighting of `ContractDeployer.ts` to be incorrect. I added the missing backtick.

### CODE REVIEW

**Comment by tinybike** [comment]
Hm....why is the travis build for this failing...?

**Comment by tomdev** [comment]
Retried the build but hitting the same error :( Seems unrelated to my changes though.

**Comment by danuker** [comment]
See PR #684

**Comment by tomdev** [comment]
Merging master back in this PR didn't go that well, retrying here: #686

**Pull request closed without merging**
