### PR TITLE
contracts: Fix SMT errors for Solidity 0.4.25.

### PR DESCRIPTION
**Pull request by cryptomental**
The InternalCompilerError does not occur anymore on a pre-release solc
0.4.25-develop.2018.7.4+commit.cde976ca.mod.Linux.g++.

* Update pramga in contracts to accept pre-released 0.4.25 Solidity compiler.
* Use explicit casts for address in certain emits.
* Change bytes32 to address casts from address() to address(uint160(uint256()))

Refs: Solidity #4341

### CODE REVIEW

**Comment by nuevoalex** [comment]
@cryptomental I attempted to run the SMT checker using your branch `npm run docker:run:test:security:smt` but encountered a few issues:

- The contracts seem to fail compilation because of the redeclarations that were added in `Order.sol` and `TradingEscapeHatch.sol`
- The Dockerfile for the smt security check has not been updated to use the experimental solc version

Could you address these issues and confirm `npm run docker:run:test:security:smt` completes successfully?

**Comment by cryptomental** [comment]
Hi @nuevoalex I will take care of this asap. I deployed the Solidity compiler pre-release to https://github.com/cryptomental/solidity/releases/tag/v0.4.25-develop.2018.7.4-smt and will update the Dockerfile. About the redeclarations I had to explicitly add them because SMT complained. I will double check that.

**Comment by cryptomental** [comment]
I pushed the Dockerfile change, the SMT run uses now pre-released solc binary. 
Once the redeclarations are removed SMT complains:

```
The following errors/warnings were returned by solc:

Warning: This is a pre-release compiler version, please do not use it in production.

trading/TradingEscapeHatch.sol:95:18: DeclarationError: Undeclared identifier.
            for (_tempOutcome = 0; _tempOutcome < _numOutcomes; ++_tempOutcome) {
```

**Comment by cryptomental** [comment]
@nuevoalex all done!

**Comment by nuevoalex** [comment]
> I pushed the Dockerfile change, the SMT run uses now pre-released solc binary.
Once the redeclarations are removed SMT complains:

This seems like a bug in compiler when SMT is enabled since compiling without SMT enabled will cause the following error:

```
Error: The following errors/warnings were returned by solc:

trading/Order.sol:134:18: DeclarationError: Identifier already declared.
            for (uint256 _i = 0; _i < _numberOfOutcomes; _i++) {
                 ^--------^
trading/Order.sol:123:14: The previous declaration is here:
        for (uint256 _i = 0; _i < _numberOfOutcomes; _i++) {
             ^--------^
```

We need the contracts to be able to compile successfully when SMT is not enabled. Seems like we're close though!

**Comment by cryptomental** [comment]
Hi @nuevoalex I asked in the Solidity GitHub space, lets wait for the answer. We are indeed very close and I hope we can close this ticket soon.

**Comment by cryptomental** [comment]
@nuevoalex I amended the PR, code is now accepted both for 0.4.24 and 0.4.24+ compiler.

**Comment by nuevoalex** [comment]
I'm still getting compilation errors on this branch with 0.4.24:

```
SolcError: /home/alex/Work/cryptomental-augur-core/source/contracts/trading/Order.sol:135:18: DeclarationError: Identifier already declared.
E                           for (uint256 _i = 0; _i < _numberOfOutcomes; _i++) {
```

**Comment by cryptomental** [comment]
Hmm let me see again.

**Comment by cryptomental** [comment]
Hi @nuevoalex I did a clean wipe of docker images, checked out clean branch and executed smt and non-smt build, all looks fine.

```
 $  rm -rf augur-core/
 $  git clone https://github.com/cryptomental/augur-core.git
 $  cd augur-core/
 $  git co bugfix/solc-0.4.25-smt-fixes 
 $  git log
 $  npm run docker:run:test:security:smt
 $  npm run docker:build
 $  npm run docker:test
```

I also had a look at the line that you pasted with the compilation error:

```
12:23:01 (bugfix/solc-0.4.25-smt-fixes) augur-core$ sed '135q;d' source/contracts/trading/Order.sol
            for (_i = 0; _i < _numberOfOutcomes; _i++) {
```

and it is different than yours. Perhaps you still had the old branch checked out when the error happened? :-) If everything is ok I hope the PR can be merged and we can close the issue.

**Comment by nuevoalex** [comment]
@cryptomental apologies, you're right I was not up to date. This looks good. Merging :)

**Pull request merged**
