### PR TITLE
Claim proceeds test

### PR DESCRIPTION
**Pull request by qqqube**

### CODE REVIEW

**Comment by tinybike** [comment]
@qqqube can you squash your commits into a single commit?  In general, please avoid commits with identical and/or uninformative messages, if you can.

**Comment by qqqube** [comment]
yeah, sorry about that. I still need to download python2.7 to run the tests so I kept committing to see the travis build outputs

**Comment by MicahZoltu** [comment]
This PR appears to include changes from the `deployment` branch.  Going to wait to review until those land so I can pick the two apart.

**Comment by MicahZoltu** [comment]
The base branch for this (deployment) has been merged into develop, so this can be rebased onto develop now.  Let me know in #dev if you want some help with the rebase/merge git magic.

**Comment by MicahZoltu** [comment]
Closing due to inactivity.  Ping me in #dev or here if this should be re-opened.

**Pull request closed without merging**
