### PR TITLE
Adding in .gitattributes file

### PR DESCRIPTION
**Pull request by rbharath**
The solidity contracts in the augur-core repo currently don't have syntax highlighting. Github recently added support for solidity syntax highlighting, but due to name conflicts, requires each repo which wants such highlighting to add in a special .gitattributes file. This PR adds this file.

Contracts look very nice with highlighting turned on (for example, see https://github.com/datamined/contracts/blob/master/contracts/DataCoin.sol), so I think it will make the contracts here more readable.

~~As a note though, note that due to a bug in the current GitHub linguist declaration for solidity, syntax highlighting won't work for contracts with pragma statements of form `pragma solidity 0.4.18;` (as opposed to statements of form `pragma solidity ^0.4.18`). See discussion here https://github.com/aragon/aragonOS/issues/231~~
Edit by @rbharath: It turns out that there wasn't a bug. The syntax highlighting just took a long time to activate but looks to be functional, even for explicit pragmas.

### CODE REVIEW

**Comment by nuevoalex** [comment]
Thanks for pointing this out! Will get it merged once the tests re-run

**Comment by MicahZoltu** [comment]
We use the explicit version form everywhere I believe, and I'm fairly against changing that.  Hopefully they'll fix the bug with the highlighter...

**Comment by rbharath** [comment]
@nuevoalex @MicahZoltu Turns out that the highlighting works fine with explicit pragmas; sorry about the confusion! (See edited note above).

The tests look to be halted though. Would you folks have any recommendations on how we can get them running again?

**Comment by joeykrug** [comment]
Just merged this change

**Pull request closed without merging**
